from .department_list import DepartmentList
from .index_view import Index_View
from .training_program_list_view import Training_Program_List_View
from .training_program_add_view import Training_Program_Add_View
from .training_program_detail_view import Training_Program_Detail_View
from .training_program_edit_view import Training_Program_Edit_View