from .department_list import DepartmentList
from .index_view import Index_View
from .training_program_list_view import Training_Program_List_View
from .training_program_add_view import Training_Program_Add_View
from .employee_detail_view import Employee_Department_View
from .employee_detail_view import Employee_Detail_View